import type { HandoffModelEntry } from './catalog-types.js';
import { Q4, Q5, Q8, DEFAULT_QUANT } from './catalog-types.js';

const OLLAMA_QUANTS = [Q4, Q5, Q8, DEFAULT_QUANT];

/**
 * Ollama-served models (local). Context defaults are conservative MacBook values;
 * the advisor overrides them per hardware. Availability is filled in at runtime
 * from `ollama list`.
 */
export const OLLAMA_CATALOG: HandoffModelEntry[] = [
  // ── Qwen ──
  {
    id: 'qwen3:4b', backend: 'ollama', label: 'qwen3:4b', family: 'qwen',
    roles: ['fast_cool', 'tool_use', 'coding_agent'], privacy: 'local', sizeClass: 'small',
    totalParamsB: 4, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 4096, safeContextTokens: 4096, maxContextTokens: 32768,
    minUnifiedMemoryGb: 8, recommendedUnifiedMemoryGb: 8, minimumMacTier: 'any',
    heatRisk: 'low', maturity: 'recommended',
    toolUseScore: 4, codingScore: 3, reasoningScore: 3, writingScore: 3, speedScore: 5,
    notes: 'tiny · fast · strong tools',
  },
  {
    id: 'qwen3:8b', backend: 'ollama', label: 'qwen3:8b', family: 'qwen',
    roles: ['default', 'fast_cool', 'tool_use', 'coding_agent', 'research_synthesis'],
    privacy: 'local', sizeClass: 'small', totalParamsB: 8, quantOptions: OLLAMA_QUANTS,
    defaultQuant: 'q4_K_M', defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 32768,
    minUnifiedMemoryGb: 8, recommendedUnifiedMemoryGb: 16, minimumMacTier: 'any',
    heatRisk: 'low', maturity: 'recommended',
    toolUseScore: 5, codingScore: 4, reasoningScore: 4, writingScore: 4, speedScore: 4,
    notes: 'default · fast · tools · coding · research',
  },
  {
    id: 'qwen3:14b', backend: 'ollama', label: 'qwen3:14b', family: 'qwen',
    roles: ['coding_agent', 'tool_use', 'reasoning_verifier', 'research_synthesis'],
    privacy: 'local', sizeClass: 'medium', totalParamsB: 14, quantOptions: OLLAMA_QUANTS,
    defaultQuant: 'q4_K_M', defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 32768,
    minUnifiedMemoryGb: 16, recommendedUnifiedMemoryGb: 24, minimumMacTier: 'apple_silicon',
    heatRisk: 'medium', maturity: 'recommended',
    toolUseScore: 5, codingScore: 4, reasoningScore: 4, writingScore: 4, speedScore: 3,
    notes: 'reasoning · tools · research · warm',
  },
  {
    id: 'qwen3:30b-a3b', backend: 'ollama', label: 'qwen3:30b-a3b', family: 'qwen',
    roles: ['coding_agent', 'tool_use', 'research_synthesis', 'long_context'],
    privacy: 'local', sizeClass: 'large', totalParamsB: 30, activeParamsB: 3, quantOptions: OLLAMA_QUANTS,
    defaultQuant: 'q4_K_M', defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 32768,
    minUnifiedMemoryGb: 24, recommendedUnifiedMemoryGb: 32, minimumMacTier: 'pro',
    heatRisk: 'high', maturity: 'advanced',
    toolUseScore: 5, codingScore: 4, reasoningScore: 4, writingScore: 4, speedScore: 3,
    notes: 'MoE · tools · hot · benchmark first',
  },
  {
    id: 'qwen3-coder:30b', backend: 'ollama', label: 'qwen3-coder:30b', family: 'qwen',
    roles: ['coding_agent', 'tool_use'], privacy: 'local', sizeClass: 'large',
    totalParamsB: 30, activeParamsB: 3, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 32768,
    minUnifiedMemoryGb: 24, recommendedUnifiedMemoryGb: 32, minimumMacTier: 'pro',
    heatRisk: 'high', maturity: 'advanced',
    toolUseScore: 5, codingScore: 5, reasoningScore: 4, writingScore: 3, speedScore: 3,
    notes: 'coding · tools · hot · benchmark first',
    aliases: ['qwen3-coder:30b-a3b', 'qwen3-coder:30b-a3b-q4_K_M'],
  },
  {
    id: 'qwen3-coder-next', backend: 'ollama', label: 'qwen3-coder-next', family: 'qwen',
    roles: ['coding_agent', 'tool_use', 'server_frontier'], privacy: 'local', sizeClass: 'xl',
    totalParamsB: 80, activeParamsB: 3, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 32768,
    minUnifiedMemoryGb: 64, recommendedUnifiedMemoryGb: 96, minimumMacTier: 'max',
    heatRisk: 'extreme', maturity: 'server_only',
    toolUseScore: 5, codingScore: 5, reasoningScore: 4, writingScore: 3, speedScore: 2,
    notes: '80B MoE · server only',
  },

  // ── Gemma (Gemma 3 shipping tags; Gemma 4 falls back automatically) ──
  {
    id: 'gemma3:4b', backend: 'ollama', label: 'gemma3:4b', family: 'gemma',
    roles: ['fast_cool', 'research_writing', 'multimodal'], privacy: 'local', sizeClass: 'small',
    totalParamsB: 4, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 4096, safeContextTokens: 4096, maxContextTokens: 32768,
    minUnifiedMemoryGb: 8, recommendedUnifiedMemoryGb: 8, minimumMacTier: 'any',
    heatRisk: 'low', maturity: 'recommended',
    toolUseScore: 3, codingScore: 2, reasoningScore: 3, writingScore: 4, speedScore: 5,
    notes: 'writing · small · weak tools',
  },
  {
    id: 'gemma3:12b', backend: 'ollama', label: 'gemma3:12b', family: 'gemma',
    roles: ['research_writing', 'research_synthesis', 'multimodal'], privacy: 'local', sizeClass: 'medium',
    totalParamsB: 12, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 32768,
    minUnifiedMemoryGb: 16, recommendedUnifiedMemoryGb: 24, minimumMacTier: 'apple_silicon',
    heatRisk: 'medium', maturity: 'recommended',
    toolUseScore: 3, codingScore: 3, reasoningScore: 3, writingScore: 5, speedScore: 3,
    notes: 'writing · research · check tools',
  },
  {
    id: 'gemma3:27b', backend: 'ollama', label: 'gemma3:27b', family: 'gemma',
    roles: ['research_writing', 'research_synthesis'], privacy: 'local', sizeClass: 'large',
    totalParamsB: 27, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 32768,
    minUnifiedMemoryGb: 24, recommendedUnifiedMemoryGb: 32, minimumMacTier: 'pro',
    heatRisk: 'high', maturity: 'advanced',
    toolUseScore: 3, codingScore: 3, reasoningScore: 4, writingScore: 5, speedScore: 2,
    notes: 'writing · large · hot',
  },

  // ── DeepSeek (reasoning/verifier) ──
  {
    id: 'deepseek-r1:1.5b', backend: 'ollama', label: 'deepseek-r1:1.5b', family: 'deepseek',
    roles: ['fast_cool', 'reasoning_verifier', 'experimental'], privacy: 'local', sizeClass: 'micro',
    totalParamsB: 1.5, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 4096, safeContextTokens: 4096, maxContextTokens: 16384,
    minUnifiedMemoryGb: 8, recommendedUnifiedMemoryGb: 8, minimumMacTier: 'any',
    heatRisk: 'low', maturity: 'experimental',
    toolUseScore: 2, codingScore: 2, reasoningScore: 3, writingScore: 2, speedScore: 5,
    notes: 'tiny · reasoning · weak tools · verifier',
  },
  {
    id: 'deepseek-r1:8b', backend: 'ollama', label: 'deepseek-r1:8b', family: 'deepseek',
    roles: ['reasoning_verifier', 'reviewer'], privacy: 'local', sizeClass: 'small',
    totalParamsB: 8, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 32768,
    minUnifiedMemoryGb: 8, recommendedUnifiedMemoryGb: 16, minimumMacTier: 'any',
    heatRisk: 'low', maturity: 'advanced',
    toolUseScore: 3, codingScore: 3, reasoningScore: 4, writingScore: 3, speedScore: 4,
    notes: 'reasoning · verifier · thinking hidden',
  },
  {
    id: 'deepseek-r1:14b', backend: 'ollama', label: 'deepseek-r1:14b', family: 'deepseek',
    roles: ['reasoning_verifier', 'reviewer'], privacy: 'local', sizeClass: 'medium',
    totalParamsB: 14, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 32768,
    minUnifiedMemoryGb: 16, recommendedUnifiedMemoryGb: 24, minimumMacTier: 'apple_silicon',
    heatRisk: 'medium', maturity: 'advanced',
    toolUseScore: 3, codingScore: 3, reasoningScore: 5, writingScore: 3, speedScore: 3,
    notes: 'reasoning · verifier · audit',
  },
  {
    id: 'deepseek-r1:32b', backend: 'ollama', label: 'deepseek-r1:32b', family: 'deepseek',
    roles: ['reasoning_verifier', 'reviewer'], privacy: 'local', sizeClass: 'large',
    totalParamsB: 32, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 32768,
    minUnifiedMemoryGb: 24, recommendedUnifiedMemoryGb: 32, minimumMacTier: 'pro',
    heatRisk: 'high', maturity: 'advanced',
    toolUseScore: 3, codingScore: 3, reasoningScore: 5, writingScore: 3, speedScore: 2,
    notes: 'deep reasoning · verifier · hot',
  },
  {
    id: 'deepseek-r1:70b', backend: 'ollama', label: 'deepseek-r1:70b', family: 'deepseek',
    roles: ['reasoning_verifier', 'server_frontier'], privacy: 'local', sizeClass: 'xl',
    totalParamsB: 70, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 32768,
    minUnifiedMemoryGb: 64, recommendedUnifiedMemoryGb: 96, minimumMacTier: 'ultra',
    heatRisk: 'extreme', maturity: 'server_only',
    toolUseScore: 3, codingScore: 4, reasoningScore: 5, writingScore: 4, speedScore: 1,
    notes: 'reasoning · server only',
  },

  // ── GPT-oss ──
  {
    id: 'gpt-oss:20b', backend: 'ollama', label: 'gpt-oss:20b', family: 'gpt_oss',
    roles: ['tool_use', 'structured_output', 'coding_agent', 'research_synthesis'],
    privacy: 'local', sizeClass: 'large', totalParamsB: 20, quantOptions: OLLAMA_QUANTS,
    defaultQuant: 'q4_K_M', defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 32768,
    minUnifiedMemoryGb: 24, recommendedUnifiedMemoryGb: 32, minimumMacTier: 'pro',
    heatRisk: 'high', maturity: 'advanced',
    toolUseScore: 5, codingScore: 4, reasoningScore: 4, writingScore: 4, speedScore: 3,
    notes: 'tools · structured output · hot · benchmark',
  },
  {
    id: 'gpt-oss:120b', backend: 'ollama', label: 'gpt-oss:120b', family: 'gpt_oss',
    roles: ['tool_use', 'structured_output', 'server_frontier'], privacy: 'local', sizeClass: 'frontier',
    totalParamsB: 120, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 32768,
    minUnifiedMemoryGb: 96, recommendedUnifiedMemoryGb: 128, minimumMacTier: 'server',
    heatRisk: 'extreme', maturity: 'server_only',
    toolUseScore: 5, codingScore: 5, reasoningScore: 5, writingScore: 4, speedScore: 1,
    notes: 'tools · server only',
  },

  // ── GLM ──
  {
    id: 'glm-4.7-flash', backend: 'ollama', label: 'glm-4.7-flash', family: 'glm',
    roles: ['long_context', 'coding_agent', 'research_synthesis'], privacy: 'local', sizeClass: 'medium',
    totalParamsB: 14, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 32768,
    minUnifiedMemoryGb: 16, recommendedUnifiedMemoryGb: 24, minimumMacTier: 'apple_silicon',
    heatRisk: 'medium', maturity: 'experimental', localAvailability: 'unknown',
    toolUseScore: 4, codingScore: 4, reasoningScore: 4, writingScore: 4, speedScore: 3,
    notes: 'long context · research · coding · verify tag',
  },

  // ── Ornith (first-class Ollama family) ──
  {
    id: 'ornith:9b', backend: 'ollama', label: 'ornith:9b', family: 'ornith',
    roles: ['coding_agent', 'tool_use', 'fast_cool'], privacy: 'local', sizeClass: 'small',
    totalParamsB: 9, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 16384,
    minUnifiedMemoryGb: 8, recommendedUnifiedMemoryGb: 16, minimumMacTier: 'any',
    heatRisk: 'low', maturity: 'recommended',
    toolUseScore: 4, codingScore: 5, reasoningScore: 3, writingScore: 3, speedScore: 4,
    notes: 'coding · tools · fast · 256K ctx',
    aliases: ['ornith:latest'],
  },
  {
    id: 'ornith:35b', backend: 'ollama', label: 'ornith:35b', family: 'ornith',
    roles: ['coding_agent', 'tool_use'], privacy: 'local', sizeClass: 'large',
    totalParamsB: 35, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 16384,
    minUnifiedMemoryGb: 32, recommendedUnifiedMemoryGb: 48, minimumMacTier: 'max',
    heatRisk: 'high', maturity: 'advanced',
    toolUseScore: 4, codingScore: 5, reasoningScore: 4, writingScore: 3, speedScore: 2,
    notes: 'coding · large · hot · benchmark first',
  },

  // ── Legacy fallbacks ──
  {
    id: 'phi4-mini-reasoning', backend: 'ollama', label: 'phi4-mini-reasoning', family: 'legacy',
    roles: ['fast_cool', 'reasoning_verifier'], privacy: 'local', sizeClass: 'small',
    totalParamsB: 4, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 4096, safeContextTokens: 4096, maxContextTokens: 16384,
    minUnifiedMemoryGb: 8, recommendedUnifiedMemoryGb: 8, minimumMacTier: 'any',
    heatRisk: 'low', maturity: 'recommended',
    toolUseScore: 2, codingScore: 2, reasoningScore: 4, writingScore: 3, speedScore: 5,
    notes: 'reasoning · fast · limited tools',
  },
  {
    id: 'phi4', backend: 'ollama', label: 'phi4', family: 'legacy',
    roles: ['research_synthesis', 'reasoning_verifier'], privacy: 'local', sizeClass: 'medium',
    totalParamsB: 14, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 16384,
    minUnifiedMemoryGb: 16, recommendedUnifiedMemoryGb: 24, minimumMacTier: 'apple_silicon',
    heatRisk: 'medium', maturity: 'advanced',
    toolUseScore: 2, codingScore: 3, reasoningScore: 4, writingScore: 4, speedScore: 3,
    notes: 'general · limited tools',
  },
  {
    id: 'llama3.1:8b', backend: 'ollama', label: 'llama3.1:8b', family: 'legacy',
    roles: ['tool_use', 'research_synthesis'], privacy: 'local', sizeClass: 'small',
    totalParamsB: 8, quantOptions: OLLAMA_QUANTS, defaultQuant: 'q4_K_M',
    defaultContextTokens: 8192, safeContextTokens: 8192, maxContextTokens: 32768,
    minUnifiedMemoryGb: 8, recommendedUnifiedMemoryGb: 16, minimumMacTier: 'any',
    heatRisk: 'low', maturity: 'advanced',
    toolUseScore: 3, codingScore: 3, reasoningScore: 3, writingScore: 3, speedScore: 4,
    notes: 'general · stable',
  },
];
