import type { HandoffModelEntry } from './catalog-types.js';
import { SERVER_QUANT } from './catalog-types.js';

const SQ = [SERVER_QUANT];

/**
 * HuggingFace (cloud, opt-in) and vLLM (self-hosted) share HF repo IDs. Privacy
 * differs by backend at selection time; catalog entries here default to the
 * safer classification and the advisor tags them cloud/self-hosted per backend.
 */
export const HF_CATALOG: HandoffModelEntry[] = [
  // Qwen
  mk('Qwen/Qwen3-4B-Instruct', 'Qwen3-4B', 'qwen', 'small', 4, ['fast_cool', 'tool_use'], 5, 3),
  mk(
    'Qwen/Qwen3-8B-Instruct',
    'Qwen3-8B',
    'qwen',
    'small',
    8,
    ['default', 'tool_use', 'coding_agent'],
    5,
    4,
  ),
  mk(
    'Qwen/Qwen3-14B-Instruct',
    'Qwen3-14B',
    'qwen',
    'medium',
    14,
    ['coding_agent', 'tool_use'],
    5,
    4,
  ),
  mk(
    'Qwen/Qwen3-30B-A3B-Instruct',
    'Qwen3-30B-A3B',
    'qwen',
    'large',
    30,
    ['coding_agent', 'tool_use'],
    5,
    4,
    3,
  ),
  mk(
    'Qwen/Qwen3-Coder-30B-A3B-Instruct',
    'Qwen3-Coder-30B',
    'qwen',
    'large',
    30,
    ['coding_agent', 'tool_use'],
    5,
    5,
    3,
  ),
  mk(
    'Qwen/Qwen3-Coder-Next',
    'Qwen3-Coder-Next',
    'qwen',
    'xl',
    80,
    ['coding_agent', 'server_frontier'],
    5,
    5,
    3,
    'server_only',
  ),
  // Gemma
  mk(
    'google/gemma-3-12b-it',
    'Gemma-3-12B',
    'gemma',
    'medium',
    12,
    ['research_writing', 'multimodal'],
    3,
    3,
  ),
  mk('google/gemma-3-27b-it', 'Gemma-3-27B', 'gemma', 'large', 27, ['research_writing'], 3, 3),
  // DeepSeek
  mk(
    'deepseek-ai/DeepSeek-R1-Distill-Qwen-7B',
    'DeepSeek-R1-7B',
    'deepseek',
    'small',
    7,
    ['reasoning_verifier'],
    3,
    3,
  ),
  mk(
    'deepseek-ai/DeepSeek-R1-Distill-Qwen-14B',
    'DeepSeek-R1-14B',
    'deepseek',
    'medium',
    14,
    ['reasoning_verifier'],
    3,
    3,
  ),
  mk(
    'deepseek-ai/DeepSeek-R1-Distill-Qwen-32B',
    'DeepSeek-R1-32B',
    'deepseek',
    'large',
    32,
    ['reasoning_verifier'],
    3,
    3,
  ),
  mk(
    'deepseek-ai/DeepSeek-V4-Flash',
    'DeepSeek-V4-Flash',
    'deepseek',
    'frontier',
    140,
    ['reasoning_verifier', 'server_frontier'],
    4,
    4,
    4,
    'cloud_only',
    'cloud_opt_in',
  ),
  mk(
    'deepseek-ai/DeepSeek-V4-Pro',
    'DeepSeek-V4-Pro',
    'deepseek',
    'frontier',
    671,
    ['reasoning_verifier', 'server_frontier'],
    5,
    5,
    5,
    'cloud_only',
    'cloud_opt_in',
  ),
  // GPT-oss
  mk(
    'openai/gpt-oss-20b',
    'gpt-oss-20b',
    'gpt_oss',
    'large',
    20,
    ['tool_use', 'structured_output'],
    5,
    4,
  ),
  mk(
    'openai/gpt-oss-120b',
    'gpt-oss-120b',
    'gpt_oss',
    'frontier',
    120,
    ['tool_use', 'server_frontier'],
    5,
    5,
    5,
    'server_only',
  ),
  // GLM
  mk(
    'zai-org/GLM-5',
    'GLM-5',
    'glm',
    'frontier',
    355,
    ['long_context', 'coding_agent', 'server_frontier'],
    5,
    5,
    5,
    'cloud_only',
    'cloud_opt_in',
  ),
  mk(
    'zai-org/GLM-5.2',
    'GLM-5.2',
    'glm',
    'frontier',
    355,
    ['long_context', 'coding_agent', 'server_frontier'],
    5,
    5,
    5,
    'cloud_only',
    'cloud_opt_in',
  ),
  // Kimi
  mk(
    'moonshotai/Kimi-K2.7-Code',
    'Kimi-K2.7-Code',
    'kimi',
    'frontier',
    1000,
    ['coding_agent', 'server_frontier'],
    5,
    5,
    5,
    'cloud_only',
    'cloud_opt_in',
  ),
  mk(
    'moonshotai/Kimi-K2.6',
    'Kimi-K2.6',
    'kimi',
    'frontier',
    1000,
    ['coding_agent', 'server_frontier'],
    5,
    5,
    5,
    'cloud_only',
    'cloud_opt_in',
  ),
  mk(
    'moonshotai/Kimi-Moonlight-16B-A3B',
    'Kimi-Moonlight-16B',
    'kimi',
    'medium',
    16,
    ['coding_agent', 'tool_use'],
    4,
    4,
    3,
  ),
  // Ornith
  mk(
    'deepreinforce-ai/Ornith-1.0-9B',
    'Ornith-9B',
    'ornith',
    'small',
    9,
    ['coding_agent', 'tool_use', 'fast_cool'],
    4,
    5,
  ),
  mk(
    'deepreinforce-ai/Ornith-1.0-31B',
    'Ornith-31B',
    'ornith',
    'large',
    31,
    ['coding_agent', 'tool_use'],
    4,
    5,
    3,
  ),
  mk(
    'deepreinforce-ai/Ornith-1.0-35B',
    'Ornith-35B',
    'ornith',
    'large',
    35,
    ['coding_agent', 'tool_use'],
    4,
    5,
    3,
  ),
  mk(
    'deepreinforce-ai/Ornith-1.0-397B',
    'Ornith-397B',
    'ornith',
    'frontier',
    397,
    ['coding_agent', 'server_frontier'],
    5,
    5,
    5,
    'server_only',
  ),
];

/** Compact constructor for remote entries (HF repo ids). */
function mk(
  id: string,
  label: string,
  family: HandoffModelEntry['family'],
  sizeClass: HandoffModelEntry['sizeClass'],
  totalParamsB: number,
  roles: HandoffModelEntry['roles'],
  toolUseScore: HandoffModelEntry['toolUseScore'],
  codingScore: HandoffModelEntry['codingScore'],
  activeParamsB?: number,
  maturity: HandoffModelEntry['maturity'] = 'advanced',
  privacy: HandoffModelEntry['privacy'] = 'self_hosted',
): HandoffModelEntry {
  const cloud = privacy === 'cloud_opt_in' || maturity === 'cloud_only';
  return {
    id,
    backend: 'hf',
    label,
    family,
    roles,
    privacy,
    sizeClass,
    totalParamsB,
    ...(activeParamsB ? { activeParamsB } : {}),
    quantOptions: SQ,
    defaultQuant: 'server_selected',
    defaultContextTokens: 8192,
    safeContextTokens: 8192,
    maxContextTokens: 131072,
    minimumMacTier: 'server',
    heatRisk: cloud ? 'low' : 'high',
    maturity,
    toolUseScore,
    codingScore,
    reasoningScore: 4,
    writingScore: 4,
    speedScore: cloud ? 4 : 2,
    notes: cloud
      ? 'Cloud model: project data may leave your machine. Requires explicit consent.'
      : 'Self-hosted (vLLM). Server must be running; quantization is server-selected.',
  };
}
